language: node_js
node_js:
  - node_js
dist: trusty
sudo: false
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm i -g npm@5.7.1 # delete once 5.7.X is out of "pre-release"
  - npm ci  